### ISSUE TITLE
Wireless medium saturation

### ISSUE THREAD

**Issue by marlenegb** [intrig-unicamp/mininet-wifi#277] opened 2019-11-25 18:10 UTC
I have this simple network: sta1 & sta2 - ap1 - s1- h1 
I want to see how the wireless medium reacts when is saturated. I have the option mode defined as ‘g’ . I tried to sent udp (iperf) data from h1 to both sta1 and sta2 with the parameter -b defined as 100 mbps, but when I see data that enters in the s1 interface that s connected to h1, it’s never 100 mbps, but always around 23 mbps for each stations, so the wireless medium never saturate. Can you tell me why it happens ? Why h1 doesn’t send he 100 mpbs each like I defined in the iperf command?
Thank you so much,
Best Regard

**Comment by ramonfontes** [comment] 2019-11-25 18:16
Is it supposed to work that way? Why? Taking into account that IEEE 802.11g supports up to 54Mbits, why should it transmit 100Mbps??? Am I missing something here?

**Comment by marlenegb** [comment] 2019-11-25 18:28
I’m not saying that the AP has to 
 transmit 100 Mbps, I’m talking about the link between h1 and s1. Before AP1, is not supposed to pass the 100 Mbps for each station and after the AP, 54Mbps, in total, for the two stations?

**Comment by ramonfontes** [comment] 2019-11-25 18:30
Could you please tell me how are you measuring the link between **h1** and **s1**? How can I reproduce the tests you're doing?

**Comment by marlenegb** [comment] 2019-11-25 20:31
i'm measuring it with tcpdump, this is the script.

info("Create a network.")
	net=Mininet_wifi(controller=RemoteController,accessPoint=OVSKernelAP,switch=OVSKernelSwitch)

	info("*** Creating nodes\n")

	###Adding the Access Point
	ap1 = net.addAccessPoint('ap1', ssid="wifi1", mode="g", protocols='OpenFlow13',channel="5",position='0,12,1')

	###Adding the Switch
	s1 = net.addSwitch('s1', protocols='OpenFlow13')

	###Adding stations
	sta1=net.addStation('sta1',mac='00:02:00:00:00:01', ip='10.0.0.1/24', position='0,12,2')
	sta2=net.addStation('sta2',mac='00:02:00:00:00:02', ip='10.0.0.2/24', position='0,12,3')

	###Adding the host
	h1 = net.addHost('h1', mac='00:02:00:00:00:04', ip='10.0.0.4/24')
		
	###Adding the controller
	c0 = net.addController('c0')

	info("*** Configuring wifi nodes\n")
	net.configureWifiNodes()

	net.addLink(sta1,ap1,clc=wmediumd)
	net.addLink(sta2,ap1,clc=wmediumd)
		
	net.addLink(h1,s1, clc=TCLink)
	net.addLink(ap1,s1, clc=TCLink)

	os.system("sudo tcpdump -i s1-eth1 -w udpuph_exp.pcap &")
	os.system("sudo tcpdump -i ap1-wlan1 -w udpupsta_exp.pcap &")

	sta1.cmd('iperf -s -u -i 1 >> udpdownsta1exp.txt &') 
	sta2.cmd('iperf -s -u -i 1 >> udpdownsta2exp.txt &') 
	
	h1.cmd(' iperf -c %s'%sta1.IP()+' -u -b 100M -t 20 &')
	h1.cmd(' iperf -c %s'%sta2.IP()+' -u -b 100M -t 20 &')

	time.sleep(20)
	
	("\n*** Running CLI\n")
	CLI_wifi(net)

	info("*** Stopping network\n")
	net.stop()

**Comment by ramonfontes** [comment] 2019-11-25 20:44
Where are the reproducibility steps? I can see only a incomplete code without instructions. If you don't tell me how to get the result you mentioned, I will be unable to help you. :( Moreover, what did you mean with `clc=wmediumd` and `clc=TCLink`?

**Comment by marlenegb** [comment] 2019-11-25 23:08
Sorry, i have more code that this and i put it here wrongly. I use clc=wmediumd because i want a wireless link between stations and AP and TClink because i want a physic one here, can you correct me if it's wrong ? 

import sys, os, time, math

from mininet.node import Controller, RemoteController, OVSKernelSwitch
from mininet.log import setLogLevel, info
from mn_wifi.node import OVSKernelAP
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi
from mn_wifi.link import wmediumd
from mininet.link import TCLink


def topology():

	info("Create a network.")
	net=Mininet_wifi(controller=RemoteController,accessPoint=OVSKernelAP,switch=OVSKernelSwitch)

	info("*** Creating nodes\n")

	###Adding the Access Point
	ap1 = net.addAccessPoint('ap1', ssid="wifi1", mode="g", protocols='OpenFlow13',channel="5",position='0,12,1')

	###Adding the Switch
	s1 = net.addSwitch('s1', protocols='OpenFlow13')

	###Adding stations
	sta1=net.addStation('sta1',mac='00:02:00:00:00:01', ip='10.0.0.1/24', position='0,12,2')
	sta2=net.addStation('sta2',mac='00:02:00:00:00:02', ip='10.0.0.2/24', position='0,12,3')

	###Adding the host
	h1 = net.addHost('h1', mac='00:02:00:00:00:04', ip='10.0.0.4/24')
		
	###Adding the controller
	c0 = net.addController('c0')

	info("*** Configuring wifi nodes\n")
	net.configureWifiNodes()

	net.addLink(sta1,ap1,clc=wmediumd)
	net.addLink(sta2,ap1,clc=wmediumd)
		
	net.addLink(h1,s1, clc=TCLink)
	net.addLink(ap1,s1, clc=TCLink)

	info("*** Starting network\n")
	net.build()
	c0.start()
	s1.start([c0])	
	ap1.start([c0])

	os.system("sudo tcpdump -i s1-eth1 -w udpuph_exp.pcap &")
	os.system("sudo tcpdump -i ap1-wlan1 -w udpupsta_exp.pcap &")

	sta1.cmd('iperf -s -u -i 1 >> udpdownsta1exp.txt &') 
	sta2.cmd('iperf -s -u -i 1 >> udpdownsta2exp.txt &') 

	h1.cmd(' iperf -c %s'%sta1.IP()+' -u -t 20  -b 100M  &')
	h1.cmd(' iperf -c %s'%sta2.IP()+' -u -t 20 -b 100M &')

	time.sleep(20)

	("\n*** Running CLI\n")
	CLI_wifi(net)

	info("*** Stopping network\n")
	net.stop()

if __name__ == '__main__':
	setLogLevel('info')
	topology()

**Comment by ramonfontes** [comment] 2019-11-25 23:12
It should be `cls` and not `clc`! **Where are the reproducibility steps????**

**Comment by marlenegb** [comment] 2019-11-25 23:30
i use ryu controller with simple_switch_13.py app
>>cd ryu/ryu/app 
>>sudo ryu-manager simple_switch_13.py
and for runnig this code i do this: sudo python topology

ps:I change the cls for link=wmedium in the mininet_wifi(), can i do this way ? 


import sys, os, time, math

from mininet.node import Controller, RemoteController, OVSKernelSwitch
from mininet.log import setLogLevel, info
from mn_wifi.node import OVSKernelAP
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi
from mn_wifi.link import wmediumd
from mininet.link import TCLink


def topology():

	info("Create a network.")
	net=Mininet_wifi(controller=RemoteController,accessPoint=OVSKernelAP,switch=OVSKernelSwitch, link=wmediumd)

	info("*** Creating nodes\n")

	###Adding the Access Point
	ap1 = net.addAccessPoint('ap1', ssid="wifi1", mode="g", protocols='OpenFlow13',channel="5",position='0,12,1')

	###Adding the Switch
	s1 = net.addSwitch('s1', protocols='OpenFlow13')

	###Adding stations
	sta1=net.addStation('sta1',mac='00:02:00:00:00:01', ip='10.0.0.1/24', position='0,12,2')
	sta2=net.addStation('sta2',mac='00:02:00:00:00:02', ip='10.0.0.2/24', position='0,12,3')

	###Adding the host
	h1 = net.addHost('h1', mac='00:02:00:00:00:04', ip='10.0.0.4/24')
		
	###Adding the controller
	c0 = net.addController('c0')

	info("*** Configuring wifi nodes\n")
	net.configureWifiNodes()

	net.addLink(sta1,ap1)
	net.addLink(sta2,ap1)
		
	net.addLink(h1,s1)
	net.addLink(ap1,s1)

	info("*** Starting network\n")
	net.build()
	c0.start()
	s1.start([c0])	
	ap1.start([c0])

	os.system("sudo tcpdump -i s1-eth1 -w udpuph_exp.pcap &")
	os.system("sudo tcpdump -i ap1-wlan1 -w udpupsta_exp.pcap &")

	sta1.cmd('iperf -s -u -i 1 >> udpdownsta1exp.txt &') 
	sta2.cmd('iperf -s -u -i 1 >> udpdownsta2exp.txt &') 

	h1.cmd(' iperf -c %s'%sta1.IP()+' -u -t 20  -b 100M  &')
	h1.cmd(' iperf -c %s'%sta2.IP()+' -u -t 20 -b 100M &')

	time.sleep(20)

	("\n*** Running CLI\n")
	CLI_wifi(net)

	info("*** Stopping network\n")
	net.stop()

if __name__ == '__main__':
	setLogLevel('info')
	topology()

**Comment by ramonfontes** [comment] 2019-11-25 23:38
> i use ryu controller with simple_switch_13.py app

- I just need to run Ryu and the results will appear? How many times I need to ask for the reproducibility steps? First time you send a wrong code (you didn't even check what was being sent). Now, I have 2 codes and you simply don't provide any information about the reproducibility steps. I'm closing this issue due to the lack of clear answers.

**Closed by ramonfontes** 2019-11-25 23:38 UTC

**Comment by marlenegb** [comment] 2019-11-25 23:47
Code:

def topology():

info("Create a network.")
net=Mininet_wifi(controller=RemoteController,accessPoint=OVSKernelAP,switch=OVSKernelSwitch, link=wmediumd)

info("*** Creating nodes\n")

###Adding the Access Point
ap1 = net.addAccessPoint('ap1', ssid="wifi1", mode="g", protocols='OpenFlow13',channel="5",position='0,12,1')

###Adding the Switch
s1 = net.addSwitch('s1', protocols='OpenFlow13')

###Adding stations
sta1=net.addStation('sta1',mac='00:02:00:00:00:01', ip='10.0.0.1/24', position='0,12,2')
sta2=net.addStation('sta2',mac='00:02:00:00:00:02', ip='10.0.0.2/24', position='0,12,3')

###Adding the host
h1 = net.addHost('h1', mac='00:02:00:00:00:04', ip='10.0.0.4/24')
	
###Adding the controller
c0 = net.addController('c0')

info("*** Configuring wifi nodes\n")
net.configureWifiNodes()

net.addLink(sta1,ap1)
net.addLink(sta2,ap1)
	
net.addLink(h1,s1)
net.addLink(ap1,s1)

info("*** Starting network\n")
net.build()
c0.start()
s1.start([c0])	
ap1.start([c0])

os.system("sudo tcpdump -i s1-eth1 -w udpuph_exp.pcap &")
os.system("sudo tcpdump -i ap1-wlan1 -w udpupsta_exp.pcap &")

sta1.cmd('iperf -s -u -i 1 >> udpdownsta1exp.txt &') 
sta2.cmd('iperf -s -u -i 1 >> udpdownsta2exp.txt &') 

h1.cmd(' iperf -c %s'%sta1.IP()+' -u -t 20  -b 100M  &')
h1.cmd(' iperf -c %s'%sta2.IP()+' -u -t 20 -b 100M &')

time.sleep(20)

("\n*** Running CLI\n")
CLI_wifi(net)

info("*** Stoppinrg network\n")
net.stop()
if name == 'main':
setLogLevel('info')
topology()


---------
Reproducibility step:
1) For Ryu Controller:
cd ryu/ryu/app 
sudo ryu-manager simple_switch_13.py

2) To running this script:
sudo python topology 

This script will save 4 files: 2 pcap files, one for s1-eth1 and another for ap1-wlan1, and saves 2 txt files, one with results for the iperf test from sta1 and another from sta2.

**Comment by ramonfontes** [comment] 2019-11-25 23:51
and then?? *.txt files don't help, since they are running from stations. How can I use the pcap file? How do I know you're checking inbound and not outbound data traffic??

**Comment by marlenegb** [comment] 2019-11-26 00:01
the txt files was just to see the downlink bandwidth. I use de pcap files to see the traffic in wireshark that is sent by the host to the stations, to confirme if it is the 100 mbps. To see the rate, i use I/O graphic in wireshark, with this filters:
filter 1) ip.dst=10.0.0.1  ; filter 2)  ip.dst==10.0.0.2
My doubt is: Why the traffic on link h1-s1 was not 100 mbps, but aproximatly 25 for each station ? Is not suposed to be 25 for each station after de AP ?

**Comment by ramonfontes** [comment] 2019-11-26 00:25
So, we have one more new information you should include in the reproducibility steps. Am I right? And everything you said was:

After 20 seconds running, this script will save 4 files: 2 pcap files, one for s1-eth1 and another for ap1-wlan1, and saves 2 txt files, one with results for the iperf test from sta1 and another from sta2.

So, I'll repeat the question one more time: what are the reproducibility steps?? There is something new I should be aware of?? I even don't know which value you've chosen for the Y axis.

Btw, I didn't notice any problem with the measurements.

**Comment by marlenegb** [comment] 2019-11-26 10:36
I use in the y axis Bits, to se the bits/sec that comes from h1 to s1. And 
Now, with this script happens two thinsgs to me:

**OR:**
 i get this results in stations (the txt files):

------------------------------------------------------------
Server listening on UDP port 5001
Receiving 1470 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 10.0.0.2 port 5001 connected with 10.0.0.4 port 33142
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 1.0 sec   126 KBytes  1.03 Mbits/sec  11.389 ms 28865/28953 (1e+02%)
[  3] 0.00-1.00 sec  7 datagrams received out-of-order
[  3]  1.0- 2.0 sec   307 KBytes  2.52 Mbits/sec   0.450 ms    0/  105 (0%)
[  3] 1.00-2.00 sec  109 datagrams received out-of-order
[  3]  2.0- 3.0 sec  1.97 MBytes  16.5 Mbits/sec  10.041 ms    0/  892 (0%)
[  3] 2.00-3.00 sec  759 datagrams received out-of-order
[  3]  3.0- 4.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3]  4.0- 5.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3]  5.0- 6.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3]  6.0- 7.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3]  7.0- 8.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3]  8.0- 9.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3]  9.0-10.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 10.0-11.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 11.0-12.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 12.0-13.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 13.0-14.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 14.0-15.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 15.0-16.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 16.0-17.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 17.0-18.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 18.0-19.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)
[  3] 19.0-20.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (0%)

And when i try "sudo mn -c", i get stuck in "***  Removing WiFi module and Configurations"
Like this: 

ubuntu@ubuntu-VirtualBox:~/tese/new_code$ sudo mn -c
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --if-exists del-br ap1 -- --if-exists del-br s1
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
( ip link del s1-eth1;ip link del s1-eth2;ip link del ap1-eth2;ip link del ap1-eth2;ip link del s1-eth2 ) 2> /dev/null
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.
***  Removing WiFi module and Configurations

And after this if i want to run again the script i have to reboot the system, because its said that the module mac_80211_hwsim is in use.

**OR**  
I get in the stations this results, that is ok for the stations:
------------------------------------------------------------
Server listening on UDP port 5001
Receiving 1470 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 10.0.0.2 port 5001 connected with 10.0.0.4 port 45098
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 1.0 sec  1.21 MBytes  10.1 Mbits/sec  49.505 ms 30583/31443 (97%)
[  3] 0.00-1.00 sec  107 datagrams received out-of-order
[  3]  1.0- 2.0 sec  1.36 MBytes  11.4 Mbits/sec   2.471 ms 1290/ 2260 (57%)
[  3] 1.00-2.00 sec  84 datagrams received out-of-order
[  3]  2.0- 3.0 sec  1.32 MBytes  11.1 Mbits/sec   1.446 ms  889/ 1831 (49%)
[  3] 2.00-3.00 sec  69 datagrams received out-of-order
[  3]  3.0- 4.0 sec  1.28 MBytes  10.7 Mbits/sec  69.233 ms  504/ 1416 (36%)
[  3] 3.00-4.00 sec  104 datagrams received out-of-order
[  3]  4.0- 5.0 sec  1.43 MBytes  12.0 Mbits/sec  131.812 ms 2239/ 3259 (69%)
[  3] 4.00-5.00 sec  127 datagrams received out-of-order
[  3]  5.0- 6.0 sec  1.28 MBytes  10.7 Mbits/sec  225.185 ms 1287/ 2198 (59%)
[  3] 5.00-6.00 sec  97 datagrams received out-of-order
[  3]  6.0- 7.0 sec  1.38 MBytes  11.6 Mbits/sec  62.355 ms 1217/ 2203 (55%)
[  3] 6.00-7.00 sec  100 datagrams received out-of-order
[  3]  7.0- 8.0 sec  1.28 MBytes  10.7 Mbits/sec  237.005 ms 1709/ 2621 (65%)
[  3] 7.00-8.00 sec  92 datagrams received out-of-order
[  3]  8.0- 9.0 sec  1.41 MBytes  11.8 Mbits/sec  221.130 ms 2466/ 3472 (71%)
[  3] 8.00-9.00 sec  138 datagrams received out-of-order
[  3]  9.0-10.0 sec  1.33 MBytes  11.1 Mbits/sec  72.334 ms 2690/ 3638 (74%)
[  3] 9.00-10.00 sec  134 datagrams received out-of-order
[  3] 10.0-11.0 sec  1.41 MBytes  11.8 Mbits/sec   0.970 ms 2775/ 3778 (73%)
[  3] 10.00-11.00 sec  104 datagrams received out-of-order
[  3] 11.0-12.0 sec  2.52 MBytes  21.2 Mbits/sec   1.407 ms 3121/ 4920 (63%)
[  3] 12.0-13.0 sec  2.19 MBytes  18.4 Mbits/sec   1.920 ms 2097/ 3662 (57%)
[  3] 13.0-14.0 sec  2.45 MBytes  20.6 Mbits/sec   1.239 ms 2158/ 3909 (55%)
[  3] 14.0-15.0 sec  2.51 MBytes  21.0 Mbits/sec   0.608 ms 1343/ 3132 (43%)
[  3] 15.0-16.0 sec  2.28 MBytes  19.1 Mbits/sec   1.282 ms 3578/ 5204 (69%)
[  3]  0.0-16.9 sec  28.4 MBytes  14.1 Mbits/sec  16.215 ms 64421/84664 (76%)
[  3] 0.00-16.93 sec  1156 datagrams received out-of-order

But in wireshark i get this for udp packets in h1-s1 link:
https://www.dropbox.com/s/ocy8w55w6g59a9i/h1-s1-link.png?dl=0
(sorry, i don't know to put images here)

**Comment by ramonfontes** [comment] 2019-11-26 11:01
As I said, I didn't notice problems with the measurements - your answers are too confusing too. Since I am not able to reproduce the same behavior, I won't continue with this thread.

**Comment by marlenegb** [comment] 2019-11-26 11:51
Can you just tell how did you measure 13000000 Bytes/sec for h1 ?

**Comment by ramonfontes** [comment] 2019-11-26 12:08
https://intrig.dca.fee.unicamp.br:8840/owncloud/index.php/s/nt7dEQbZySoZeW9
